---
title: "Cox_models_all_variables"
author: "Marietta_Dalamanga"
date: "2024-07-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(survival)
library(survminer)
library(pec)
```

load dairy datasets
```{r}
train_data <- read_csv("./data/dairy_training_data.csv", show_col_types = FALSE)
validation_data <- read_csv("./data/dairy_validation_data.csv", show_col_types = FALSE)
```



```{r}
variables <- variable.names(train_data)
variables <- variables[-c(2, 3)]
variables 
```



create Survival objects for each variable
```{r}
survival_object <- sapply(variables, function(x) as.formula(paste("Surv(months_alive, status) ~ ", x)))
```


Create cox model for each variable
```{r}

cox_model <- lapply(survival_object, function(x){coxph(x, data=train_data)})
cox_model[41]
```

Create a dataframe with the results of Cox model
```{r}
get_results <- lapply(cox_model, function(x){
  overview <- summary(x)
  log_death_hazard <- coef(overview)[1]
  p_value <- signif(overview$wald["pvalue"], digits=2)
  likelihood_test <- signif(overview$sctest["test"], digits=2)
  beta <- signif(overview$coef[1], digits=2)
  hazard_ratio <- signif(overview$coef[2], digits=2)
  hr_conf_lower <- signif(overview$conf.int[3], 2)
  hr_conf_upper <- signif(overview$conf.int[4], 2)
  hazard_ratio <- paste0(hazard_ratio, " (", 
                         hr_conf_lower, "-", hr_conf_upper, ")")
  results <- c(beta, hazard_ratio, likelihood_test, p_value)
  names(results) <- c("beta", "change in hazard (95% CI for hazard ratio)", "likelihood_test", "p_value")
  return(results)
  })
```



```{r}
results_for_all <- t(as.data.frame(get_results, check.names = FALSE))
results_for_all <- as.data.frame(results_for_all)
results_for_all
```



```{r}
variables <- variables[-c(55, 59, 60, 62, 63, 64, 65)]
variables 
```

```{r}
colSums(train_data)
```


```{r}
cox_multi <- coxph(Surv(months_alive, status) ~ Omagh + ab_ba747dbffafe62fb8bea541fd72df6d8c7afcb2f, data = train_data)
cox_multi
```

Modelling attempt with all variables
```{r}
cox_multi <- coxph(Surv(months_alive, status) ~  Total_Conditions_per_Animal + T_2M + RH2M + No + TB + FACTORY.DAMAGE +
                                  FASCIOLIASIS + PLEURISY + NAD + NEPHRITIS + SCAR.TISSUE + INJECTION.SITES + ABSCESS.PYAEMIA +
                                  CONTAMINATION + ACTINO + BRUISING + HYDRONEPHROSIS + TELANGECTASIS + PETECHAE.HAEMORRHAGES +
                                   PERICARDITIS + FEVERED + PLEUR.PNEUMONIA.GENERAL + PERITONITIS + PLEUR.PNEUMONIA.LOCAL + 
                                   RESIDUES + HAEMATOMA + ARTHRITIS + TB.GENERALISED + OEDEMA + EMACIATION + Armagh + 
                                  Ballymena + Coleraine + Dungannon + Enniskillen + LondonDerry + Mallusk + Newry + NtArds + 
                                  Omagh + ab_4f71277e271f09349a4d6d5f6c05acf635652015 + ab_6f7d51dd8564e05e279faa791f97894ef141a4db +
                                  ab_32d8a591f643abd1ff6a998b128403c8962a55d8 + ab_f833f5d69610136a115182502764c803be97ee16 + 
                                  ab_94003c4910d6c601a698a3258918fc822b88dd0d + ab_332a6a1d2843f367c160a1c7c3fb2a28f0f8909e + 
                                  ab_568a97a7e2a6685902dd553c276b1837e0ebf06b + ab_ae2f3299f13dc08c27a4bd4586901243017aa1c0 + 
                                  ab_9032d4760ad9a99eb868b5d854cbae1492401dda + ab_8a60fb1b9b40ed0fdc5d3c061e9388972f3bdce4 + 
                                  ab_87fc1df58026b8a228f9c4afa002b2b7722a8f09 + ab_cdf0a11f70869c640bfe6c23935ff3da4acfb7b0 + 
                                  ab_ba747dbffafe62fb8bea541fd72df6d8c7afcb2f + FR + HOL + F + B + M + died_on_abattoir + died_on_farm, 
                   data = train_data)
summary(cox_multi)
```


Now we get rid of problematic variables
```{r}
cox_multi_limited <- coxph(Surv(months_alive, status) ~  Total_Conditions_per_Animal + T_2M + RH2M + No + TB + FACTORY.DAMAGE +
                                  FASCIOLIASIS + PLEURISY + NAD + NEPHRITIS + SCAR.TISSUE + INJECTION.SITES + ABSCESS.PYAEMIA +
                                  CONTAMINATION + ACTINO + BRUISING + HYDRONEPHROSIS + TELANGECTASIS + PETECHAE.HAEMORRHAGES +
                                   PERICARDITIS + FEVERED + PLEUR.PNEUMONIA.GENERAL + PERITONITIS + PLEUR.PNEUMONIA.LOCAL + 
                                   RESIDUES + HAEMATOMA + ARTHRITIS + TB.GENERALISED + OEDEMA + EMACIATION + Armagh + 
                                  Ballymena + Coleraine + Dungannon + Enniskillen + LondonDerry + Mallusk + Newry + NtArds + 
                                  ab_4f71277e271f09349a4d6d5f6c05acf635652015 + ab_6f7d51dd8564e05e279faa791f97894ef141a4db +
                                  ab_32d8a591f643abd1ff6a998b128403c8962a55d8 + ab_f833f5d69610136a115182502764c803be97ee16 + 
                                  ab_94003c4910d6c601a698a3258918fc822b88dd0d + ab_332a6a1d2843f367c160a1c7c3fb2a28f0f8909e + 
                                  ab_568a97a7e2a6685902dd553c276b1837e0ebf06b + ab_ae2f3299f13dc08c27a4bd4586901243017aa1c0 + 
                                  ab_9032d4760ad9a99eb868b5d854cbae1492401dda + ab_8a60fb1b9b40ed0fdc5d3c061e9388972f3bdce4 + 
                                  ab_87fc1df58026b8a228f9c4afa002b2b7722a8f09 + ab_cdf0a11f70869c640bfe6c23935ff3da4acfb7b0 + 
                                  ab_ba747dbffafe62fb8bea541fd72df6d8c7afcb2f + FR  + F + B + died_on_abattoir, 
                   data = train_data)
summary(cox_multi_limited)
```





```{r}
selectedSupermodel <- selectCox(Surv(train_data$months_alive, train_data$status) ~ 
                                  Total_Conditions_per_Animal + T_2M + RH2M + No + TB + FACTORY.DAMAGE +
                                  FASCIOLIASIS + PLEURISY + NAD + NEPHRITIS + SCAR.TISSUE + INJECTION.SITES + ABSCESS.PYAEMIA +
                                  CONTAMINATION + ACTINO + BRUISING + HYDRONEPHROSIS + TELANGECTASIS + PETECHAE.HAEMORRHAGES +
                                   PERICARDITIS + FEVERED + PLEUR.PNEUMONIA.GENERAL + PERITONITIS + PLEUR.PNEUMONIA.LOCAL + 
                                   RESIDUES + HAEMATOMA + ARTHRITIS + TB.GENERALISED + OEDEMA + EMACIATION + Armagh + 
                                  Ballymena + Coleraine + Dungannon + Enniskillen + LondonDerry + Mallusk + Newry + NtArds + 
                                  ab_4f71277e271f09349a4d6d5f6c05acf635652015 + ab_6f7d51dd8564e05e279faa791f97894ef141a4db +
                                  ab_32d8a591f643abd1ff6a998b128403c8962a55d8 + ab_f833f5d69610136a115182502764c803be97ee16 + 
                                  ab_94003c4910d6c601a698a3258918fc822b88dd0d + ab_332a6a1d2843f367c160a1c7c3fb2a28f0f8909e + 
                                  ab_568a97a7e2a6685902dd553c276b1837e0ebf06b + ab_ae2f3299f13dc08c27a4bd4586901243017aa1c0 + 
                                  ab_9032d4760ad9a99eb868b5d854cbae1492401dda + ab_8a60fb1b9b40ed0fdc5d3c061e9388972f3bdce4 + 
                                  ab_87fc1df58026b8a228f9c4afa002b2b7722a8f09 + ab_cdf0a11f70869c640bfe6c23935ff3da4acfb7b0 + 
                                  ab_ba747dbffafe62fb8bea541fd72df6d8c7afcb2f + FR + F + B + died_on_abattoir 
                                , data=train_data)

selectedSupermodel
```




```{r}
fit_superCox <- coxph(Surv(train_data$months_alive, train_data$status) ~ Total_Conditions_per_Animal + T_2M + RH2M + TB + FACTORY.DAMAGE + 
FASCIOLIASIS + PLEURISY + NAD + INJECTION.SITES + ABSCESS.PYAEMIA + CONTAMINATION + ACTINO + BRUISING + TELANGECTASIS + PETECHAE.HAEMORRHAGES + 
PERICARDITIS + FEVERED + PLEUR.PNEUMONIA.GENERAL + PERITONITIS + PLEUR.PNEUMONIA.LOCAL + RESIDUES + HAEMATOMA + ARTHRITIS + TB.GENERALISED + 
EMACIATION + Armagh + Ballymena + Coleraine + Dungannon + Enniskillen + LondonDerry + Newry + NtArds + ab_4f71277e271f09349a4d6d5f6c05acf635652015 + ab_6f7d51dd8564e05e279faa791f97894ef141a4db + ab_32d8a591f643abd1ff6a998b128403c8962a55d8 + ab_f833f5d69610136a115182502764c803be97ee16 + ab_94003c4910d6c601a698a3258918fc822b88dd0d + ab_568a97a7e2a6685902dd553c276b1837e0ebf06b + ab_9032d4760ad9a99eb868b5d854cbae1492401dda + ab_8a60fb1b9b40ed0fdc5d3c061e9388972f3bdce4 + ab_87fc1df58026b8a228f9c4afa002b2b7722a8f09 + ab_cdf0a11f70869c640bfe6c23935ff3da4acfb7b0 + ab_ba747dbffafe62fb8bea541fd72df6d8c7afcb2f + FR + F + B + died_on_abattoir, data=train_data)


fit_superCox
```

visualise the selectedsupermodel
```{r}
super_cox_train <- survfit(fit_superCox, data=train_data)

ggsurvplot(super_cox_train, ggtheme = theme_minimal())
```


```{r}
validation_output <- validation_data[3]
validation_output
new_data <- validation_data[-c(3)]
super_cox_validation <- survfit(fit_superCox, data=new_data)
summary(super_cox_validation)
baseline_survival <- survfit(Surv(validation_data$months_alive, validation_data$status) ~1, data=validation_data)
fit <- list(test = super_cox_validation, baseline = baseline_survival)
ggsurvplot(fit, combine = TRUE, 
           risk.table = TRUE,                  # Add risk table
           conf.int = TRUE,                    # Add confidence interval
           conf.int.style = "step",            # CI style, use "step" or "ribbon"
           censor = FALSE,                     # Remove censor points
           tables.theme = theme_cleantable(),  # Clean risk table
           palette = "jco")
```

```{r}
fit <- list(test = super_cox_validation, train = super_cox_train)
ggsurvplot(fit,  # Combine curves
           risk.table = TRUE,                  # Add risk table
           conf.int = TRUE,                    # Add confidence interval
           conf.int.style = "step",            # CI style, use "step" or "ribbon"
           censor = FALSE,                     # Remove censor points
           tables.theme = theme_cleantable(),  # Clean risk table
           palette = "jco")
ggsurvplot(survfit(fit_superCox, data=validation_data), ggtheme = theme_minimal())
```


```{r}
library(prodlim)
library(lava)
library(riskRegression)
library(survival)

```





```{r}
# survival
dlearn <- SimSurv(40)
dval <- SimSurv(100)

f <- coxph(Surv(time,status)~X1+X2,data=dlearn,x=TRUE,y=TRUE)

cf=calPlot(f,time=3,data=dval)
print(cf)
plot(cf)
```

```{r}

g <- coxph(Surv(time,status)~X2,data=dlearn,x=TRUE,y=TRUE)
cf2=calPlot(list("Cox regression X1+X2"=f,"Cox regression X2"=g),
time=3,
type="risk",
data=dval)
print(cf2)

plot(cf2)
calPlot(f,time=3,data=dval,type="survival")
calPlot(f,time=3,data=dval,bars=TRUE,pseudo=FALSE)
calPlot(f,time=3,data=dval,bars=TRUE,type="risk",pseudo=FALSE)
## show a red line which follows the hanging bars
calPlot(f,time=3,data=dval,bars=TRUE,hanging=TRUE)
a <- calPlot(f,time=3,data=dval,bars=TRUE,hanging=TRUE,abline.col=NULL)
lines(c(0,1,ceiling(a$xcoord)),
c(a$offset[1],a$offset,a$offset[length(a$offset)]),
col=2,lwd=5,type="s")
calPlot(f,time=3,data=dval,bars=TRUE,type="risk",hanging=TRUE)
set.seed(13)
m <- crModel()
regression(m, from = "X1", to = "eventtime1") <- 1
regression(m, from = "X2", to = "eventtime1") <- 1
m <- addvar(m,c("X3","X4","X5"))
distribution(m, "X1") <- binomial.lvm()
distribution(m, "X4") <- binomial.lvm()
d1 <- sim(m,100)
d2 <- sim(m,100)
csc <- CSC(Hist(time,event)~X1+X2+X3+X4+X5,data=d1)
fgr <- FGR(Hist(time,event)~X1+X2+X3+X4+X5,data=d1,cause=1)
if ((requireNamespace("cmprsk",quietly=TRUE))){
predict.crr <- cmprsk:::predict.crr
cf3=calPlot(list("Cause-specific Cox"=csc,"Fine-Gray"=fgr),
time=5,
legend.x=-0.3,
legend.y=1.35,
ylab="Observed event status",
legend.legend=c("Cause-specific Cox regression","Fine-Gray regression"),
legend.xpd=NA)
print(cf3)
plot(cf3)
b1 <- calPlot(list("Fine-Gray"=fgr),time=5,bars=TRUE,hanging=FALSE)
print(b1)
plot(b1)
calPlot(fgr,time=5,bars=TRUE,hanging=TRUE)
}
```




