---
title: "Playground"
output: html_notebook
---

```{r}
library(scales)
library(survival)
library(survminer)
# library(gtsummary) cannot install this library
# library(glmulti) cannot install the package
```
run model for all variables
```{r}
glmulti.cox.ph <- glmulti(Surv(breed_wide_data$months_alive, breed_wide_data$status) ~ ., data = breed_wide_data, 
    level = 1,             # to exclude interactions (use 2 for pairwise interaction terms)
    method = "h",          # exhaustive method
    crit = "aic",          # another option is "bic"
    report = TRUE,        # No interim reports 
    plotty = FALSE,        # No plot
    fitfunction = "coxph")
```



```{r}
km_fit_1 <- survfit(Surv(time, status) ~ 1, data = lung)
summary(km_fit_1$surv)
log_log_s <- log(-log(km_fit_1$surv))
log_t <- log(km_fit_1$time)
log_log_s

km_fit_1_lm <- lm(log_log_s ~ log_t)
km_fit_1_lm %>%
  broom::augment() %>%
  ggplot(aes(x = log_t)) +
  geom_point(aes(y = log_log_s)) +
  geom_line(aes(y = .fitted), linetype = 2, color = "goldenrod") +
  theme_light()
```

list of colnames
```{r}
v <- colnames(lung[, c(1, 4:10)])

v
lung
```




create Survival objects for each variable
```{r}
survival_object <- sapply(v, function(x) as.formula(paste("Surv(time, status) ~ ", x)))

```

Create cox model for each variable
```{r}
cox_model <- lapply(survival_object, function(x){coxph(x, data=lung)})
cox_model
summary(cox_model)
q <- summary(cox_model$inst)
q
signif(q$wald["test"], digits=2)
signif(q$coef[1], digits=2)
signif(q$coef[2], digits=2)
signif(q$conf.int[4], 2)

```
```{r}
q$sctest["test"]

```


Create a dataframe with the results of Cox model
```{r}
get_results <- lapply(cox_model, function(x){
  overview <- summary(x)
  log_death_hazard <- coef(overview)[1]
  p_value <- signif(overview$wald["pvalue"], digits=2)
  likelihood_test <- signif(overview$sctest["test"], digits=2)
  beta <- signif(overview$coef[1], digits=2)
  hazard_ratio <- signif(overview$coef[2], digits=2)
  hr_conf_lower <- signif(overview$conf.int[3], 2)
  hr_conf_upper <- signif(overview$conf.int[4], 2)
  hazard_ratio <- paste0(hazard_ratio, " (", 
                         hr_conf_lower, "-", hr_conf_upper, ")")
  results <- c(beta, hazard_ratio, likelihood_test, p_value)
  names(results) <- c("beta", "change in hazard (95% CI for hazard ratio)", "likelihood_test", "p_value")
  return(results)
  })
```



```{r}
results_for_all <- t(as.data.frame(get_results, check.names = FALSE))
results_for_all <- as.data.frame(results_for_all)
results_for_all

```




