---
title: "log_rank_tests"
author: "Marietta_Dalamanga"
date: "2024-07-14"
output:
  pdf_document: default
  html_document: default
---



```{r}
library(tidyverse)
library(dplyr)
library(tidyr)
library(caret)
library(ggplot2)
library(scales)
library(survival)
library(survminer)
library(caret)
library(sampling)
```



#### Log_rank test for beef_data


```{r}
beef_data <- read.csv("./data/beef_data.csv")

dairy_data <- read.csv("dairy_data.csv")
```

```{r}
colnames(dairy_data)
```

create samples for each dataset
```{r}
subgroups <- c("Sex")
```

```{r}
set.seed(123)
sample_size <- 0.2 * nrow(dairy_data)
stratum_sizes <- table(dairy_data[subgroups]) * (0.2*nrow(dairy_data))/ nrow(dairy_data)
stratum_sizes[stratum_sizes==0] <- 1
strata_sample <- strata(dairy_data, stratanames= subgroups, 
                        size=as.vector(stratum_sizes), method = "srswor")
sample_data <- getdata(dairy_data, strata_sample)
print(sample_data)
```

```{r}
chi_square_test <- functon(original_data, sample_data, variable) {
  chisq_test <- chisq.test(table(original_data[[variable]]), table(sample_data[[variable]]))
  return(chisq_test)
}

t_test <- functon(original_data, sample_data, variable) {
  t_test_res <- t.test(original_data[[variable]], sample_data[[variable]])
  return(t_test_res)
}

chi_square_results <- lapply(subgroups, function(var) chi_square_test(dairy_data, sample_data, var))

t_test_results <-t_test(dairy_data, sample_data, "months_alive")


print(chi_square_results)
print(t_test_results)
```



get 10% sample of the beef data using the caret package and setting y=months alive

```{r}
set.seed(123)

beef_sample <- createDataPartition(y=beef_data$months_alive, p=0.1, list=FALSE)
beef_sample <-beef
```

