---
title: "Kaplan_Meier"
author: "Marietta_Dalamanga"
date: "2024-07-04"
output: html_document
---

## Survival analysis, Kaplan-Meier curves

```{r}
library(tidyverse)
library(dplyr)
library(tidyr)
library(survival)
library(survminer)
library(data.table)
library(ggplot2)
library(ggpubr)
```


```{r}
survival_data_without_outliers <- read.csv("data_without_outliers.csv")

```

```{r}
colnames(survival_data_without_outliers)
```

### Baseline survival curve
years
```{r}

baseline_survival_fit <- survfit(Surv(years_alive, status) ~ 1, data = survival_data_without_outliers)
summary(baseline_survival_fit)$table

```

```{r}
baseline_survival <- data.frame(time = baseline_survival_fit$time,
                  n.risk = baseline_survival_fit$n.risk,
                  n.event = baseline_survival_fit$n.event,
                  n.censor = baseline_survival_fit$n.censor,
                  surv = baseline_survival_fit$surv,
                  upper = baseline_survival_fit$upper,
                  lower = baseline_survival_fit$lower
                  )
baseline_survival
```

```{r}
km_baseline_years <- ggsurvplot(baseline_survival_fit,
          pval = FALSE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw()# Change ggplot2 theme
          )+
  labs(title="Baseline survival in years", x="Years", y="Survival_probability") 
km_baseline_years
ggsave("km_baseline_years.png", plot=km_baseline_years$plot, width = 8, height = 6)
ggsave("risk_table_of_baseline_sirvival.png", plot=km_baseline_years$table)
```



Days
```{r}

baseline_survival_fit_days <- survfit(Surv(days_alive, status) ~ 1, data = survival_data_without_outliers)
summary(baseline_survival_fit)$table

```


```{r}
baseline_survival_days <- data.frame(time = baseline_survival_fit_days$time,
                  n.risk = baseline_survival_fit_days$n.risk,
                  n.event = baseline_survival_fit_days$n.event,
                  n.censor = baseline_survival_fit_days$n.censor,
                  surv = baseline_survival_fit_days$surv,
                  upper = baseline_survival_fit_days$upper,
                  lower = baseline_survival_fit_days$lower
                  )

baseline_survival_days
```



```{r}
km_baseline_days <- ggsurvplot(baseline_survival_fit_days,
          pval = FALSE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
          palette = "blue")+
  labs(title="Baseline survival in days", x="Days", y="Survival_probability") 
km_baseline_days
ggsave("km_baseline_days.png", plot=km_baseline_years$plot, width = 8, height = 6)
ggsave("risk_table_of_baseline_sirvival_days.png", plot=km_baseline_days$table)
```



### survival curve for sex

years
```{r}

sex_fit_years <- survfit(Surv(years_alive, status) ~ Sex, data=survival_data_without_outliers)
                     
```


```{r}

summary(sex_fit_years)$table

```

```{r}
survival_sex_years <- data.frame(time = sex_fit_years$time,
                  n.risk = sex_fit_years$n.risk,
                  n.event = sex_fit_years$n.event,
                  n.censor = sex_fit_years$n.censor,
                  surv = sex_fit_years$surv,
                  upper = sex_fit_years$upper,
                  lower = sex_fit_years$lower
                  )
survival_sex_years
```


```{r}
km_sex_years <- ggsurvplot(sex_fit_years,
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "Sex", # Change risk table color by groups
          linetype = "Sex", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
          palette = c("#E7B800", "#2E9FDF", "#4E800f"))+
  labs(title="Survival in years vs sex", x="Years", y="Survival_probability") 

ggsave("km_sex_years.png", plot=km_sex_years$plot, width = 8, height = 6)
ggsave("risk_table_km_sex_years.png", plot=km_sex_years$table)
km_sex_years

```

days
```{r}

sex_fit_days <- survfit(Surv(days_alive, status) ~ Sex, data=survival_data_without_outliers)
                     
```


```{r}

summary(sex_fit_days)$table

```

```{r}
survival_sex_days <- data.frame(time = sex_fit_days$time,
                  n.risk = sex_fit_days$n.risk,
                  n.event = sex_fit_days$n.event,
                  n.censor = sex_fit_days$n.censor,
                  surv = sex_fit_days$surv,
                  upper = sex_fit_days$upper,
                  lower = sex_fit_days$lower
                  )
survival_sex_days
```


```{r}
km_sex_days <- ggsurvplot(sex_fit_days,
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "Sex", # Change risk table color by groups
          linetype = "Sex", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
          palette = c("#E7B800", "#2E9FDF", "#4E800f"))+
    labs(title="Survival in years vs sex", x="Days", y="Survival_probability") 

ggsave("km_sex_days.png", plot=km_sex_days$plot, width = 8, height = 6)
ggsave("risk_table_km_sex_days.png", plot=km_sex_days$table)
km_sex_days
```


### survival curve for place of death

years
```{r}

place_of_death_fit_years <- survfit(Surv(years_alive, status) ~ Abattoir_._Died_on_Farm, data=survival_data_without_outliers)
                     
```


```{r}

summary(place_of_death_fit_years)$table

```

```{r}
survival_place_of_death_years <- data.frame(time = place_of_death_fit_years$time,
                  n.risk = place_of_death_fit_years$n.risk,
                  n.event = place_of_death_fit_years$n.event,
                  n.censor = place_of_death_fit_years$n.censor,
                  surv = place_of_death_fit_years$surv,
                  upper = place_of_death_fit_years$upper,
                  lower = place_of_death_fit_years$lower
                  )
survival_place_of_death_years
```


```{r}
km_place_of_death_years <- ggsurvplot(place_of_death_fit_years,
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "Abattoir_._Died_on_Farm", # Change risk table color by groups
          linetype = "Abattoir_._Died_on_Farm", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
          palette = c("#E7B800", "#2E9FDF")) +
  labs(title="Survival in years vs place of death", x="Years", y="Survival_probability") 

ggsave("km_place_of_death_years.png", plot=km_place_of_death_years$plot, width = 8, height = 6)
ggsave("risk_table_km_place_of_death_years.png", plot=km_place_of_death_years$table)
km_place_of_death_years

```

days
```{r}

place_of_death_fit_days <- survfit(Surv(days_alive, status) ~ Abattoir_._Died_on_Farm, data=survival_data_without_outliers)
                     
```


```{r}

summary(place_of_death_fit_days)$table

```

```{r}
survival_place_of_death_days <- data.frame(time = place_of_death_fit_days$time,
                  n.risk = place_of_death_fit_days$n.risk,
                  n.event = place_of_death_fit_days$n.event,
                  n.censor = place_of_death_fit_days$n.censor,
                  surv = place_of_death_fit_days$surv,
                  upper = place_of_death_fit_days$upper,
                  lower = place_of_death_fit_days$lower
                  )
survival_place_of_death_days
```


```{r}
km_place_of_death_days <- ggsurvplot(place_of_death_fit_days,
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "Abattoir_._Died_on_Farm", # Change risk table color by groups
          linetype = "Abattoir_._Died_on_Farm", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
          palette = c("#E7B800", "#2E9FDF"))+
    labs(title="Survival in years vs place of death", x="Days", y="Survival_probability") 

ggsave("km_place_of_death_days.png", plot=km_place_of_death_days$plot, width = 8, height = 6)
ggsave("risk_table_km_place_of_death_days.png", plot=km_place_of_death_days$table)
km_place_of_death_days

```


Type of production
years
```{r}

production_fit_years <- survfit(Surv(years_alive, status) ~ Beef_or_Dairy, data=survival_data_without_outliers)
                     
```


```{r}

summary(production_fit_years)$table

```

```{r}
survival_production_years <- data.frame(time = production_fit_years$time,
                  n.risk = production_fit_years$n.risk,
                  n.event = production_fit_years$n.event,
                  n.censor = production_fit_years$n.censor,
                  surv = production_fit_years$surv,
                  upper = production_fit_years$upper,
                  lower = production_fit_years$lower
                  )
survival_production_years
```


```{r}
km_production_years <- ggsurvplot(production_fit_years,
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "Beef_or_Dairy", # Change risk table color by groups
          linetype = "Beef_or_Dairy", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
          palette = c("#E7B800", "#2E9FDF")) +
      labs(title="Survival in years vs type of production", x="Years", y="Survival_probability") 

ggsave("km_production_years.png", plot=km_production_years$plot, width = 8, height = 6)
ggsave("risk_table_km_production_years.png", plot=km_production_years$table)
km_production_years
  
```


days
```{r}

production_fit_days <- survfit(Surv(days_alive, status) ~ Beef_or_Dairy, data=survival_data_without_outliers)
                     
```


```{r}

summary(production_fit_days)$table

```

```{r}
survival_production_days <- data.frame(time = production_fit_days$time,
                  n.risk = production_fit_days$n.risk,
                  n.event = production_fit_days$n.event,
                  n.censor = production_fit_days$n.censor,
                  surv = production_fit_days$surv,
                  upper = production_fit_days$upper,
                  lower = production_fit_days$lower
                  )
survival_production_days
```


```{r}
km_production_days <- ggsurvplot(production_fit_days,
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "Beef_or_Dairy", # Change risk table color by groups
          linetype = "Beef_or_Dairy", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
          palette = c("#E7B800", "#2E9FDF")) +
        labs(title="Survival in years vs type of production", x="Years", y="Survival probability") 

ggsave("km_production_days.png", plot=km_production_days$plot, width = 8, height = 6)
ggsave("risk_table_km_production_days.png", plot=km_production_days$table)
km_production_days
```


years
```{r}


subset_of_conditions_1_2_3 <- survival_data_without_outliers %>%
  subset(survival_data$Total_Conditions_per_Animal==1 |survival_data$Total_Conditions_per_Animal==2 | survival_data$Total_Conditions_per_Animal==3)

subset_of_conditions_4_5_6 <- survival_data_without_outliers %>%
  subset(survival_data$Total_Conditions_per_Animal==4 |survival_data$Total_Conditions_per_Animal==5 | survival_data$Total_Conditions_per_Animal==6)

subset_of_conditions_7_8_9 <- survival_data_without_outliers %>%
  subset(survival_data$Total_Conditions_per_Animal==7 |survival_data$Total_Conditions_per_Animal==8 | survival_data$Total_Conditions_per_Animal==9)

total_conditions_fit_years <- survfit(Surv(years_alive, status) ~ Total_Conditions_per_Animal, data=survival_data_without_outliers)
subset_conditions_fit_years_1_2_3<- survfit(Surv(years_alive, status) ~ Total_Conditions_per_Animal, data=subset_of_conditions_1_2_3)
subset_conditions_fit_years_4_5_6<- survfit(Surv(years_alive, status) ~ Total_Conditions_per_Animal, data=subset_of_conditions_4_5_6)
subset_conditions_fit_years_7_8_9<- survfit(Surv(years_alive, status) ~ Total_Conditions_per_Animal, data=subset_of_conditions_7_8_9)
```


```{r}

summary(total_conditions_fit_years)$table

```

```{r}
survival_total_conditions_years <- data.frame(time = total_conditions_fit_years$time,
                  n.risk = total_conditions_fit_years$n.risk,
                  n.event = total_conditions_fit_years$n.event,
                  n.censor = total_conditions_fit_years$n.censor,
                  surv = total_conditions_fit_years$surv,
                  upper = total_conditions_fit_years$upper,
                  lower = total_conditions_fit_years$lower
                  )
survival_total_conditions_years
```


```{r}
subset_1_total_conditions_years <- ggsurvplot(subset_conditions_fit_years_1_2_3, 
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.y.text = FALSE,
          risk.table.col = "Total_Conditions_per_Animal", # Change risk table color by groups
          linetype = "Total_Conditions_per_Animal", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
        ) +
  labs(title="Survival in years vs total post-mortem conditions", x="Years", y="Survival probability") 
ggsave("subset_1_total_conditions_years.png", plot=subset_1_total_conditions_years$plot, width = 8, height = 6)
ggsave("subset_1_total_conditions_years.png", plot=subset_1_total_conditions_years$table)
subset_1_total_conditions_years
```
```{r}
subset_2_total_conditions_years <- ggsurvplot(subset_conditions_fit_years_4_5_6, 
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.y.text = FALSE,
          risk.table.col = "Total_Conditions_per_Animal", # Change risk table color by groups
          linetype = "Total_Conditions_per_Animal", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
        ) +
  labs(title="Survival in years vs total post-mortem conditions", x="Years", y="Survival probability") 
ggsave("subset_2_total_conditions_years.png", plot=subset_2_total_conditions_years$plot, width = 8, height = 6)
ggsave("subset_2_total_conditions_years.png", plot=subset_2_total_conditions_years$table)
subset_2_total_conditions_years
```

```{r}
subset_3_total_conditions_years <- ggsurvplot(subset_conditions_fit_years_7_8_9, 
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.y.text = FALSE,
          risk.table.col = "Total_Conditions_per_Animal", # Change risk table color by groups
          linetype = "Total_Conditions_per_Animal", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
        ) +
  labs(title="Survival in years vs total post-mortem conditions", x="Years", y="Survival probability") 
ggsave("subset_3_total_conditions_years.png", plot=subset_3_total_conditions_years$plot, width = 8, height = 6)
ggsave("subset_3_total_conditions_years.png", plot=subset_3_total_conditions_years$table)
subset_3_total_conditions_years
```



days
```{r}

total_conditions_fit_days <- survfit(Surv(days_alive, status) ~ Total_Conditions_per_Animal, data=survival_data_without_outliers)
                     
```


```{r}

summary(total_conditions_fit_days)$table

```

```{r}
survival_total_conditions_days <- data.frame(time = total_conditions_fit_days$time,
                  n.risk = total_conditions_fit_days$n.risk,
                  n.event = total_conditions_fit_days$n.event,
                  n.censor = total_conditions_fit_days$n.censor,
                  surv = total_conditions_fit_days$surv,
                  upper = total_conditions_fit_days$upper,
                  lower = total_conditions_fit_days$lower
                  )
survival_total_conditions_days
```


```{r}
km_total_conditions_days <- ggsurvplot(total_conditions_fit_days,
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "Total_Conditions_per_Animal", # Change risk table color by groups
          linetype = "Total_Conditions_per_Animal", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
        ) +
  labs(title="Survival in days vs total post-mortem conditions", x="Days", y="Survival probability") 
ggsave("km_total_conditions_days.png", plot=km_total_conditions_days$plot, width = 8, height = 6)
ggsave("km_total_conditions_days.png", plot=km_total_conditions_days$table)
km_total_conditions_days
```
```{r}
subset_conditions_fit_days_1_2_3 <- survfit(Surv(days_alive, status) ~ Total_Conditions_per_Animal, data=subset_of_conditions_1_2_3)
subset_conditions_fit_days_4_5_6 <- survfit(Surv(days_alive, status) ~ Total_Conditions_per_Animal, data=subset_of_conditions_4_5_6)
subset_conditions_fit_days_7_8_9 <- survfit(Surv(days_alive, status) ~ Total_Conditions_per_Animal, data=subset_of_conditions_7_8_9)
```

```{r}
subset_1_total_conditions_days <- ggsurvplot(subset_conditions_fit_days_1_2_3, 
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.y.text = FALSE,
          risk.table.col = "Total_Conditions_per_Animal", # Change risk table color by groups
          linetype = "Total_Conditions_per_Animal", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
        ) +
  labs(title="Survival in years vs total post-mortem conditions", x="Years", y="Survival probability") 
ggsave("subset_1_total_conditions_days.png", plot=subset_1_total_conditions_days$plot, width = 8, height = 6)
ggsave("subset_1_total_conditions_days.png", plot=subset_1_total_conditions_days$table)
subset_1_total_conditions_days
```

```{r}
subset_2_total_conditions_days <- ggsurvplot(subset_conditions_fit_days_4_5_6, 
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.y.text = FALSE,
          risk.table.col = "Total_Conditions_per_Animal", # Change risk table color by groups
          linetype = "Total_Conditions_per_Animal", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
        ) +
  labs(title="Survival in years vs total post-mortem conditions", x="Days", y="Survival probability") 
ggsave("subset_2_total_conditions_days.png", plot=subset_2_total_conditions_days$plot, width = 8, height = 6)
ggsave("subset_2_total_conditions_days.png", plot=subset_2_total_conditions_days$table)
subset_2_total_conditions_days
```


```{r}
subset_3_total_conditions_days <- ggsurvplot(subset_conditions_fit_days_7_8_9, 
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.y.text = FALSE,
          risk.table.col = "Total_Conditions_per_Animal", # Change risk table color by groups
          linetype = "Total_Conditions_per_Animal", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
        ) +
  labs(title="Survival in years vs total post-mortem conditions", x="Days", y="Survival probability") 
ggsave("subset_3_total_conditions_days.png", plot=subset_3_total_conditions_days$plot, width = 8, height = 6)
ggsave("subset_3_total_conditions_days.png", plot=subset_3_total_conditions_days$table)
subset_3_total_conditions_days
```


DVO_code
years
```{r}

DVO_fit_years <- survfit(Surv(years_alive, status) ~ Dvo_Code, data=survival_data_without_outliers)
                     
```


```{r}

summary(DVO_fit_years)$table

```

```{r}
survival_DVO_years <- data.frame(time = DVO_fit_years$time,
                  n.risk = DVO_fit_years$n.risk,
                  n.event = DVO_fit_years$n.event,
                  n.censor = DVO_fit_years$n.censor,
                  surv = DVO_fit_years$surv,
                  upper = DVO_fit_years$upper,
                  lower = DVO_fit_years$lower
                  )
survival_DVO_years
```


```{r}
ggsurvplot(DVO_fit_years,
          pval = TRUE, conf.int = TRUE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "Dvo_Code", # Change risk table color by groups
          linetype = "Dvo_Code", # Change line type by groups
          surv.median.line = "hv", # Specify median survival
          ggtheme = theme_bw(), # Change ggplot2 theme
)
```

days
```{r}

DVO_fit_days <- survfit(Surv(days_alive, status) ~ Dvo_Code, data=survival_data)
                     
```


```{r}

summary(DVO_fit_days)$table

```

```{r}
survival_DVO_days <- data.frame(time = DVO_fit_days$time,
                  n.risk = DVO_fit_days$n.risk,
                  n.event = DVO_fit_days$n.event,
                  n.censor = DVO_fit_days$n.censor,
                  surv = DVO_fit_days$surv,
                  upper = DVO_fit_days$upper,
                  lower = DVO_fit_days$lower
                  )
survival_DVO_days
```




Conditions
years
```{r}
condition_columns <- c(colnames(survival_data))
condition_columns[17:91]
                     
```


```{r}

surv_obj_days <- Surv(time = survival_data_without_outliers$days_alive, event = survival_data_without_outliers$status)
surv_obj_years <- Surv(time = survival_data_without_outliers$years_alive, event = survival_data_without_outliers$status)

```

```{r}
# Initialize an empty list to store the plots
# plot_list_days <- list()
# plot_list_years <- list()

# Loop through the columns 16 to 90 for one-hot encoded conditions
for (i in 17:91) {
  condition_name <- colnames(survival_data)[i]
  
  # Fit survival models for the condition
  fit_days <- survfit(surv_obj_days ~ survival_data[[i]])
  fit_years <- survfit(surv_obj_years ~ survival_data[[i]])
  
  # Create plots for days
  plot_days <- ggsurvplot(
    fit_days,
    data = survival_data,
    pval = TRUE,
    conf.int = TRUE,
    risk.table = TRUE,
    title = paste("Survival Curve for", condition_name, "(Days)"),
    xlab = "Time (Days)",
    ylab = "Survival Probability"
  )
  
  # Create plots for years
  plot_years <- ggsurvplot(
    fit_years,
    data = survival_data,
    pval = TRUE,
    conf.int = TRUE,
    risk.table = TRUE,
    title = paste("Survival Curve for", condition_name, "(Years)"),
    xlab = "Time (Years)",
    ylab = "Survival Probability"
  )
  
  # Add plots to the list
  plot_list_days[[condition_name]] <- plot_days$plot
  plot_list_years[[condition_name]] <- plot_years$plot
}

```



```{r}
# Combine the plots using arrange_ggsurvplots
combined_plot_days <- arrange_ggsurvplots(plot_list_days, print = FALSE)
combined_plot_years <- arrange_ggsurvplots(plot_list_years, print = FALSE)

# Print the combined plots
print(combined_plot_days)
print(combined_plot_years)

```


```{r}
condition_columns <- c("No", "SEPTICAEMIA", "ENDOCARDITIS", "TELANGECTASIS", 
                       "FACTORY.DAMAGE", "CONTAMINATION", "ABSCESS.PYAEMIA", 
                       "NAD", "FLUKE.DAMAGE", "BRUISING", "NEPHRITIS", 
                       "FASCIOLIASIS", "PERITONITIS", "TB", 
                       "PLEUR.PNEUMONIA.GENERAL", "PERICARDITIS", "ACTINO", 
                       "RESIDUES", "HYDRONEPHROSIS", "HAEMATOMA", 
                       "ARTHRITIS", "OEDEMA", "PETECHAE.HAEMORRHAGES", 
                       "TB.GENERALISED", "PLEURISY", "PLEUR.PNEUMONIA.LOCAL", 
                       "CYSTICERCUS.VIABLE", "EMACIATION", "SCAR.TISSUE", 
                       "FEVERED", "PYLEONEPHRITIS", "PNEUMONIA", 
                       "INJECTION.SITES", "ANAEMIA", "JAUNDICE", 
                       "NEPHRITIS.NEPHROSIS", "NEPHROSIS", "DETAIN", 
                       "PREG.STATUS", "CONGESTION", "MASTITIS", 
                       "MULTIPLE.ABSCESS", "INFARCTS", "URAEMIA", 
                       "SEPTIC.PERITONITIS", "FRACTURE", "ILL.BLED", 
                       "OTHER.PATHOLOGY", "CIRRHOSIS", 
                       "CYSTICERCUS.NON.VIABLE", "SUSPECT.TUMOURS", 
                       "OTHER.PROCESSING", "ABNORMAL.COLOUR", "BURSITIS", 
                       "TSE.SAMPLE", "ABNORMAL.ODOUR", "XANTHOSIS", 
                       "POLYARTHRITIS", "NECROSIS", "MELANOMA", 
                       "WOUNDS", "ENTERITIS", "EOSINOPHILIC.MYOSITIS", 
                       "ASCITIES", "EXCESS.TEETH", "SARCOCYSTIS", 
                       "PIGMENTATION", "BLOOD.SPLASH", "DEAD.ON.ARRIVAL", 
                       "TSE.SAMPLE.ASSOCIATES", "PARASITES", "OVER.30.MONTHS", 
                       "LUNG.WORM", "TSE.FAILURE", "NO.AM.INSPECTION")

# Initialize lists to store the plots and risk tables
# plot_list_days <- list()
# risk_table_list_days <- list()
# plot_list_years <- list()
# risk_table_list_years <- list()

# Loop through the condition columns
for (i in 45:48) {
  # Fit survival models for the condition
  condition_name <- condition_columns[i]
  fit_days <- survfit(surv_obj_days ~ survival_data[[condition_name]])
  fit_years <- survfit(surv_obj_years ~ survival_data[[condition_name]])
  
  # Create plots for days
  plot_days <- ggsurvplot(
    fit_days,
    data = survival_data,
    pval = TRUE,
    conf.int = TRUE,
    risk.table = FALSE,
    title = paste("Survival Curve for", condition_name, "(Days)"),
    xlab = "Time (Days)",
    ylab = "Survival Probability"
  )
  
  print(plot_days)
  
  # # Create plots for years
  # plot_years <- ggsurvplot(
  #   fit_years,
  #   data = survival_data,
  #   pval = TRUE,
  #   conf.int = TRUE,
  #   risk.table = TRUE,
  #   title = paste("Survival Curve for", condition_name, "(Years)"),
  #   xlab = "Time (Years)",
  #   ylab = "Survival Probability"
  # )
  
  # # Add only the plot and risk table components to the lists
  # plot_list_days[[condition_name]] <- plot_days$plot
  # risk_table_list_days[[condition_name]] <- plot_days$table
  # plot_list_years[[condition_name]] <- plot_years$plot
  # risk_table_list_years[[condition_name]] <- plot_years$table
}

# # Combine the plots using ggarrange
# combined_plot_days <- ggarrange(plotlist = plot_list_days, ncol = 3, nrow = 3, common.legend = TRUE)
# combined_risk_table_days <- ggarrange(plotlist = risk_table_list_days, ncol = 3, nrow = 3, common.legend = TRUE)
# 
# combined_plot_years <- ggarrange(plotlist = plot_list_years, ncol = 3, nrow = 3, common.legend = TRUE)
# combined_risk_table_years <- ggarrange(plotlist = risk_table_list_years, ncol = 3, nrow = 3, common.legend = TRUE)
# 
# # Save the combined plots with specific width and height
# ggsave("combined_plot_days.png", combined_plot_days, width = 20, height = 15)
# ggsave("combined_risk_table_days.png", combined_risk_table_days, width = 20, height = 15)
# 
# ggsave("combined_plot_years.png", combined_plot_years, width = 20, height = 15)
# ggsave("combined_risk_table_years.png", combined_risk_table_years, width = 20, height = 15)
# 
# # Optionally, you can also just print them to the output device with specific dimensions
# print(combined_plot_days)
# print(combined_risk_table_days)
# print(combined_plot_years)
# print(combined_risk_table_years)
```


```{r}
condition_columns <- c("No", "SEPTICAEMIA", "ENDOCARDITIS", "TELANGECTASIS", 
                       "FACTORY.DAMAGE", "CONTAMINATION", "ABSCESS.PYAEMIA", 
                       "NAD", "FLUKE.DAMAGE", "BRUISING", "NEPHRITIS", 
                       "FASCIOLIASIS", "PERITONITIS", "TB", 
                       "PLEUR.PNEUMONIA.GENERAL", "PERICARDITIS", "ACTINO", 
                       "RESIDUES", "HYDRONEPHROSIS", "HAEMATOMA", 
                       "ARTHRITIS", "OEDEMA", "PETECHAE.HAEMORRHAGES", 
                       "TB.GENERALISED", "PLEURISY", "PLEUR.PNEUMONIA.LOCAL", 
                       "CYSTICERCUS.VIABLE", "EMACIATION", "SCAR.TISSUE", 
                       "FEVERED", "PYLEONEPHRITIS", "PNEUMONIA", 
                       "INJECTION.SITES", "ANAEMIA", "JAUNDICE", 
                       "NEPHRITIS.NEPHROSIS", "NEPHROSIS", "DETAIN", 
                       "PREG.STATUS", "CONGESTION", "MASTITIS", 
                       "MULTIPLE.ABSCESS", "INFARCTS", "URAEMIA", 
                       "SEPTIC.PERITONITIS", "FRACTURE", "ILL.BLED", 
                       "OTHER.PATHOLOGY", "CIRRHOSIS", 
                       "CYSTICERCUS.NON.VIABLE", "SUSPECT.TUMOURS", 
                       "OTHER.PROCESSING", "ABNORMAL.COLOUR", "BURSITIS", 
                       "TSE.SAMPLE", "ABNORMAL.ODOUR", "XANTHOSIS", 
                       "POLYARTHRITIS", "NECROSIS", "MELANOMA", 
                       "WOUNDS", "ENTERITIS", "EOSINOPHILIC.MYOSITIS", 
                       "ASCITIES", "EXCESS.TEETH", "SARCOCYSTIS", 
                       "PIGMENTATION", "BLOOD.SPLASH", "DEAD.ON.ARRIVAL", 
                       "TSE.SAMPLE.ASSOCIATES", "PARASITES", "OVER.30.MONTHS", 
                       "LUNG.WORM", "TSE.FAILURE", "NO.AM.INSPECTION")

# Loop through the condition columns
for (i in 2:75) {
  # Fit survival models for the condition
  condition_name <- condition_columns[i]
  fit_days <- survfit(surv_obj_days ~ survival_data[[condition_name]])
  fit_years <- survfit(surv_obj_years ~ survival_data[[condition_name]])
  
  # Create plots for days
  plot_days <- ggsurvplot(
    fit_days,
    data = survival_data,
    pval = TRUE,
    conf.int = TRUE,
    risk.table = FALSE,
    title = paste("Survival Curve for", condition_name, "(Days)"),
    xlab = "Time (Days)",
    ylab = "Survival Probability"
  )
  
  print(plot_days)
  ggsave(paste("bycondition/",condition_name, ".png"), plot=plot_days$plot, width = 8, height = 6)
}

```


One hot encoding for breed
```{r}
# Create a column for each unique breed
breed_wide_data <- survival_data_without_outliers %>%
  mutate(BreedPresent = 1) %>%
  pivot_wider(names_from = Breed, values_from = BreedPresent, values_fill = list(ConditionPresent = 0))
```


```{r}
breed_wide_data[is.na(breed_wide_data)] <- 0
breed_wide_data
```

```{r}
surv_obj_days <- Surv(time = breed_wide_data$days_alive, event = breed_wide_data$status)
surv_obj_years <- Surv(time = breed_wide_data$years_alive, event = breed_wide_data$status)
```


Plot survival curves for each breed
```{r}
breed_columns <- c("HOL", "FR", "LIM", "AA", "HER", "BB", "CH","MB","DAQ","SHB","SIM" ,"FKV", "SH","AYR" ,"SAL" ,"SBR","SWR", "JER" ,"DEX" ,"LH",
                   "NR","BGA" ,"SHD","IM","LNR","PAR","ROT","GAL","LUI","ST","MRI","DR","HI","AU","MAJ","PIE","WP","KE" ,"EA","SD","ROM","BW","STL",
                   "CHI","BI", "BAZ","SPK","BAR","GU","BDM","GE","UNK","WAG","WG","CHL","WB","BU","TYB","AR","BBR","GLO","ALL","BRA","DEV","JEX",
                   "CAN","BAL","BRB","LBW","BLG","LAK", "MAR","ENP","FRE","BMS","NOR","BAN","SU","RPL","GAY","MG","BEE","ARM","GAS","MAL","VAN","DN",
                   "VA","PUS","PIN","ANK","BRH","AUB","SI","GRB","LID")
length(breed_columns)
# Loop through the condition columns
for (i in 1:96) {
  # Fit survival models for the condition
  breed_name <- breed_columns[i]
  fit_days <- survfit(surv_obj_days ~ breed_wide_data[[breed_name]])
  fit_years <- survfit(surv_obj_years ~ breed_wide_data[[breed_name]])
  
  # Create plots for days
  plot_days <- ggsurvplot(
    fit_days,
    data = breed_wide_data,
    pval = TRUE,
    conf.int = TRUE,
    risk.table = FALSE,
    title = paste("Survival Curve for", breed_name, "(Days)"),
    xlab = "Time (Days)",
    ylab = "Survival Probability"
  )
  
  print(plot_days)
  ggsave(paste("bybreed/",breed_name, ".png"), plot=plot_days$plot, width = 8, height = 6)
}
```

